import type { EmployeeProfile } from "./types";

export type EmployeeProfileFieldOwnership = "employee" | "hrd" | "hidden";
export type EmployeeProfileSection =
  | "personal"
  | "address"
  | "identity"
  | "education"
  | "certification"
  | "training"
  | "employment"
  | "career"
  | "attendance"
  | "payroll"
  | "emergency";
export type EmployeeProfileFieldType =
  | "text"
  | "email"
  | "phone"
  | "date"
  | "select"
  | "boolean"
  | "document"
  | "currency"
  | "textarea"
  | "address";

export type EmployeeProfileFieldMeta = {
  key: keyof EmployeeProfile | string;
  label: string;
  section: EmployeeProfileSection;
  description: string;
  ownership: EmployeeProfileFieldOwnership;
  editableByEmployee: boolean;
  visibleToEmployee: boolean;
  editableByHRD: boolean;
  visibleToHRD: boolean;
  fieldType: EmployeeProfileFieldType;
  relatedCollection?: string;
  options?: { value: string; label: string }[];
};

export const employeeFormFields: EmployeeProfileFieldMeta[] = [
  {
    key: "fullName",
    label: "Nama Lengkap",
    section: "personal",
    description: "Nama resmi sesuai KTP.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "nickName",
    label: "Nama Panggilan",
    section: "personal",
    description: "Nama sehari-hari yang biasa dipakai.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "birthPlace",
    label: "Tempat Lahir",
    section: "personal",
    description: "Kota atau kabupaten kelahiran.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "birthDate",
    label: "Tanggal Lahir",
    section: "personal",
    description: "Tanggal lahir dalam format YYYY-MM-DD.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "date",
  },
  {
    key: "gender",
    label: "Jenis Kelamin",
    section: "personal",
    description: "Jenis kelamin yang bersangkutan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "select",
  },
  {
    key: "maritalStatus",
    label: "Status Pernikahan",
    section: "personal",
    description: "Status pernikahan karyawan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "select",
  },
  {
    key: "religion",
    label: "Agama",
    section: "personal",
    description: "Agama yang tercatat.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "nationality",
    label: "Kewarganegaraan",
    section: "personal",
    description: "Kewarganegaraan yang berlaku.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "phone",
    label: "Nomor Telepon",
    section: "personal",
    description: "Nomor telepon pribadi yang aktif.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "phone",
  },
  {
    key: "personalEmail",
    label: "Email Pribadi",
    section: "personal",
    description: "Email pribadi untuk komunikasi HRD.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "email",
  },
  {
    key: "profilePhotoUrl",
    label: "Foto Profil",
    section: "personal",
    description: "Foto yang ditampilkan di profil internal.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "document",
  },
  {
    key: "addressKtp",
    label: "Alamat KTP",
    section: "address",
    description: "Alamat sesuai KTP / identitas resmi.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "address",
  },
  {
    key: "addressCurrent",
    label: "Alamat Domisili",
    section: "address",
    description: "Alamat tempat tinggal saat ini.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "textarea",
  },
  {
    key: "isDomicileSameAsKtp",
    label: "Domisili sama dengan KTP",
    section: "address",
    description: "Tandai jika alamat domisili sama dengan alamat KTP.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "boolean",
  },
  {
    key: "nik",
    label: "Nomor KTP / NIK",
    section: "identity",
    description: "Nomor identitas KTP yang valid.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "ktpPhotoUrl",
    label: "Bukti Foto KTP",
    section: "identity",
    description: "Foto KTP untuk verifikasi HRD.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "document",
    relatedCollection: "employee_profiles/{uid}/documents",
  },
  {
    key: "simNumber",
    label: "Nomor SIM",
    section: "identity",
    description: "Nomor SIM jika tersedia.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "simPhotoUrl",
    label: "Bukti Foto SIM",
    section: "identity",
    description: "Foto SIM untuk arsip dan verifikasi.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "document",
    relatedCollection: "employee_profiles/{uid}/documents",
  },
  {
    key: "npwp",
    label: "NPWP",
    section: "identity",
    description: "Nomor NPWP bagi yang memiliki.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "npwpPhotoUrl",
    label: "Bukti NPWP",
    section: "identity",
    description: "Foto atau dokumen NPWP.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "document",
    relatedCollection: "employee_profiles/{uid}/documents",
  },
  {
    key: "bpjsKesehatan",
    label: "No. BPJS Kesehatan",
    section: "identity",
    description: "Nomor BPJS Kesehatan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "bpjsKetenagakerjaan",
    label: "No. BPJS Ketenagakerjaan",
    section: "identity",
    description: "Nomor BPJS Ketenagakerjaan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "bankName",
    label: "Nama Bank",
    section: "identity",
    description: "Nama bank untuk pembayaran gaji.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "bankAccountNumber",
    label: "Nomor Rekening",
    section: "identity",
    description: "Nomor rekening untuk payroll.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "bankAccountHolderName",
    label: "Nama Pemilik Rekening",
    section: "identity",
    description: "Nama pemegang rekening bank.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "bankDocumentUrl",
    label: "Bukti Rekening",
    section: "identity",
    description: "Foto buku tabungan atau rekening.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "document",
    relatedCollection: "employee_profiles/{uid}/documents",
  },
  {
    key: "emergencyContactName",
    label: "Nama Kontak Darurat",
    section: "emergency",
    description: "Nama orang yang bisa dihubungi saat darurat.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "emergencyContactRelation",
    label: "Hubungan",
    section: "emergency",
    description: "Hubungan kontak darurat dengan karyawan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "emergencyContactPhone",
    label: "Telepon Kontak Darurat",
    section: "emergency",
    description: "Nomor telepon kontak darurat.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "phone",
  },
  {
    key: "emergencyContactAddress",
    label: "Alamat Kontak Darurat",
    section: "emergency",
    description: "Alamat kontak darurat jika diperlukan.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "textarea",
  },
  {
    key: "education",
    label: "Pendidikan Terakhir",
    section: "education",
    description: "Riwayat pendidikan formal.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "textarea",
    relatedCollection: "employee_profiles/{uid}/educations",
  },
  {
    key: "certifications",
    label: "Sertifikasi",
    section: "certification",
    description: "Daftar sertifikasi profesional.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "textarea",
    relatedCollection: "employee_profiles/{uid}/certifications",
  },
  {
    key: "trainingHistory",
    label: "Riwayat Pelatihan",
    section: "training",
    description: "Pelatihan dan workshop yang diikuti.",
    ownership: "employee",
    editableByEmployee: true,
    visibleToEmployee: true,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "textarea",
    relatedCollection: "employee_profiles/{uid}/certifications",
  },
];

export const hrdPanelFields: EmployeeProfileFieldMeta[] = [
  {
    key: "employeeNumber",
    label: "Nomor Induk Karyawan (NIK)",
    section: "employment",
    description: "Nomor karyawan internal yang ditetapkan HRD.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "positionTitle",
    label: "Jabatan / Posisi",
    section: "employment",
    description: "Posisi kerja yang ditetapkan HRD.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "division",
    label: "Divisi / Bagian",
    section: "employment",
    description: "Unit kerja sesuai organisasi.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "department",
    label: "Departemen",
    section: "employment",
    description: "Departemen administratif karyawan.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "brandName",
    label: "Brand / Perusahaan",
    section: "employment",
    description: "Unit brand atau perusahaan tempat bekerja.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "managerName",
    label: "Manager / Atasan",
    section: "employment",
    description: "Nama atasan langsung.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "workLocation",
    label: "Lokasi Kerja",
    section: "employment",
    description: "Lokasi kantor atau remote.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "joinDate",
    label: "Tanggal Mulai Bekerja",
    section: "employment",
    description: "Tanggal pertama masuk kerja.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "date",
  },
  {
    key: "contractEndDate",
    label: "Tanggal Akhir Kontrak",
    section: "employment",
    description: "Tanggal akhir kontrak jika ada.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "date",
  },
  {
    key: "contractType",
    label: "Jenis Kontrak Kerja",
    section: "employment",
    description: "Jenis kontrak seperti PKWT / KWTT.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "select",
    options: [
      { value: "karyawan", label: "Karyawan" },
      { value: "magang", label: "Magang" },
      { value: "training", label: "Training" },
      { value: "kontrak", label: "Kontrak" },
      { value: "outsourcing", label: "Outsourcing" },
    ],
  },
  {
    key: "employmentStatus",
    label: "Status Kerja",
    section: "employment",
    description: "Status aktif, probation, berhenti, atau terminasi.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "select",
  },
  {
    key: "employmentStage",
    label: "Stage Kepegawaian",
    section: "employment",
    description: "Tahapan pekerjaan internal (intern/probation/active).",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "select",
  },
  {
    key: "probationEndDate",
    label: "Akhir Probation",
    section: "employment",
    description: "Tanggal selesainya masa probation.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "date",
  },
  {
    key: "identityVerificationStatus",
    label: "Status Verifikasi Identitas",
    section: "identity",
    description: "Status verifikasi dokumen identitas oleh HRD.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "select",
    options: [
      { value: "pending", label: "Menunggu" },
      { value: "verified", label: "Diverifikasi" },
      { value: "rejected", label: "Ditolak" },
    ],
  },
  {
    key: "documentVerificationStatus",
    label: "Status Verifikasi Dokumen",
    section: "identity",
    description: "Status verifikasi dokumen administrasi.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: true,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "select",
    options: [
      { value: "pending", label: "Menunggu" },
      { value: "verified", label: "Diverifikasi" },
      { value: "rejected", label: "Ditolak" },
    ],
  },
  {
    key: "hrdNotes",
    label: "Catatan HRD",
    section: "career",
    description: "Catatan internal HRD yang hanya untuk tim HR.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "textarea",
  },
  {
    key: "internalNotes",
    label: "Catatan Internal",
    section: "career",
    description: "Catatan rahasia, penilaian, atau arsip internal.",
    ownership: "hrd",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "textarea",
  },
];

export const hiddenStoredFields: EmployeeProfileFieldMeta[] = [
  {
    key: "payrollSummary",
    label: "Ringkasan Payroll",
    section: "payroll",
    description:
      "Ringkasan gaji dan potongan yang disimpan untuk HRD dan sistem.",
    ownership: "hidden",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "currency",
    relatedCollection: "employee_profiles/{uid}/payroll_records",
  },
  {
    key: "careerEvents",
    label: "Riwayat Karier",
    section: "career",
    description: "Log promosi, mutasi, appraisal, penghargaan, dan sanksi.",
    ownership: "hidden",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "textarea",
    relatedCollection: "employee_profiles/{uid}/career_events",
  },
  {
    key: "leaveBalance",
    label: "Saldo Cuti",
    section: "attendance",
    description: "Saldo cuti tahunan dan sakit yang dihitung oleh sistem.",
    ownership: "hidden",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: true,
    visibleToHRD: true,
    fieldType: "text",
  },
  {
    key: "attendanceRecords",
    label: "Rekam Absensi",
    section: "attendance",
    description: "Data absensi harian yang disimpan secara terpisah.",
    ownership: "hidden",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
    relatedCollection: "attendance_records/{uid}",
  },
  {
    key: "leaveRequests",
    label: "Pengajuan Cuti",
    section: "attendance",
    description: "Riwayat pengajuan izin/cuti yang dikelola sistem.",
    ownership: "hidden",
    editableByEmployee: false,
    visibleToEmployee: false,
    editableByHRD: false,
    visibleToHRD: true,
    fieldType: "text",
    relatedCollection: "leave_requests/{uid}",
  },
];
